import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import AuthGate from "./Components/AuthGate";
import 'dotenv/config';

import * as GetAPI from "./GetFromApi";
import * as SendAPI from "./SendToApi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  /**
   * calls the GetAPI to repopulate its data
   */
  async function fetchData(){
    await SendAPI.regenerateSchedule();
    await GetAPI.getFromBackendApi("Instructors");
    await GetAPI.getFromBackendApi("Students");
    await GetAPI.getFromBackendApi("Sections");
  }

  fetchData();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar></Navbar>
        <AuthGate>{children}</AuthGate>
        <Footer></Footer>
      </body>
    </html>
  );
}
